---
exit:
  except:
  - triggers
  script:
  - env
  - id
  - touch /vol/rr/gitlab-builds/test
  - ps
  - exit 0
  tags:
  - auth-rr

git-sync:
  script:
  - eval `ssh-agent`
  - echo "$PUSH_KEY" | ssh-add -
  - ssh-add -L
  - git sync-remote git@github.com:edgemaster/test.git git@gitlab.doc.ic.ac.uk:tw1509/test.git
  - ssh-agent -k
  only:
  - triggers
