exit:
  except:
    - triggers

  script:
    - ps axjf
    - id
    - env

github:
  stage: deploy
  only:
    - triggers
  script:
    - "eval `ssh-agent`"
    - git remote show -n origin
    - ssh-add -l
    - ssh-agent -k

#  artifacts:
#    paths:
#      - "*"
